---
version: '3'
services:
  freqtrade:
    #image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    image: freqtradeorg/freqtrade:develop_freqairl
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.develop"
    restart: "no"
    container_name: freqtrade
    volumes:
      # - "./user_data:/freqtrade/user_data"
      - "./user_data:/freqtrade/user_data"
      - "./user_data/conf:/freqtrade/user_data/conf"
      - "./user_data/strategies:/freqtrade/user_data/strategies"
      - "./optimize/space:/freqtrade/optimize/space"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      hyperopt
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --config /freqtrade/user_data/strategies/config_freqaiRL_spot_telegram.json
      --hyperopt-loss ScalpingTradeHyperOptLoss
      --freqaimodel ReinforcementLearner
      --strategy-path /freqtrade/user_data/strategies
      --strategy FreqaiRLStrategyWPv1
      --timerange 20230101-20230530
      --timeframe 15m
      -e 3000
      --spaces buy sell roi

    #############
      # plot-dataframe
      # --logfile /freqtrade/user_data/logs/freqtrade.log
      # --config /freqtrade/user_data/strategies/config_freqaiRL_spot_telegram.json
      # --freqaimodel MyRLModel
      # --strategy-path /freqtrade/user_data/strategies
      # --strategy FreqaiRLStrategyHybrid
      # --timerange 20221224-20230224




    ######## Backtesting ##########
      # backtesting
      # --logfile /freqtrade/user_data/logs/freqtrade.log
      # --config /freqtrade/user_data/strategies/config_freqaiRL_spot_telegram.json
      # --freqaimodel MyRLModel
      # --strategy-path /freqtrade/user_data/strategies
      # --strategy FreqaiRLStrategy
      # --timerange 20221224-20230224

     ######## Hyper-opt ##########
      # hyperopt
      # --logfile /freqtrade/user_data/logs/freqtrade.log
      # --config /freqtrade/user_data/strategies/config_freqaiRL_spot_telegram.json
      # --hyperopt-loss ProfitDrawDownHyperOptLoss
      # --freqaimodel MyRLModel
      # --strategy-path /freqtrade/user_data/strategies
      # --strategy FreqaiRLStrategyHybrid
      # --timerange 20221224-20230224
      # --timeframe 15m
      # -e 100
      # --spaces  stoploss trailing roi

    #######  Freqai  ########
      # trade
      # --logfile /freqtrade/user_data/logs/freqtrade.log
      # --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      # --config /freqtrade/user_data/strategies/config_freqai_spot_telegram.json
      # --freqaimodel MyRLModel
      # --strategy-path /freqtrade/user_data/strategies
      # --strategy FreqaiRLStrategyHybrid


   ######## Download data ##########
      # download-data
      # --config /freqtrade/user_data/strategies/config_freqaiRL_spot_telegram.json
      # --timerange 20200201-
      # --timeframes 5m 15m 30m 1h 4h 1d

      
  