---
version: '3'
services:
  freqtrade:
    #image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    image: freqtradeorg/freqtrade:develop_freqairl
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.develop"
    restart: "always"
    container_name: freqtrade
    volumes:
      # - "./user_data:/freqtrade/user_data"
      - "./user_data:/freqtrade/user_data"
      - "./user_data/models/bot:/freqtrade/user_data/models/bot"
      - "./user_data/conf:/freqtrade/user_data/conf"
      - "./user_data/strategies:/freqtrade/user_data/strategies"
      # - "./optimize/space:/freqtrade/optimize/space"
      # - "./freqai:/frestrade/freqai"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      backtesting
      --config /freqtrade/user_data/conf/config_freqaiRL_spot_telegram.json
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --freqaimodel MyRLModelv8
      --strategy-path /freqtrade/user_data/strategies
      --strategy FreqaiRLStrategy_buy_hodl_03_cdl
      --timerange 20240124-20240224



    #############
      # plot-dataframe
      # --logfile /freqtrade/user_data/logs/freqtrade.log
      # --config /freqtrade/user_data/conf/config_freqaiRL_spot_telegram.json
      # --freqaimodel MyRLModel
      # --strategy-path /freqtrade/user_data/strategies
      # --strategy FreqaiRLStrategyHybrid
      # --timerange 20240124-20240224

    ######## Backtesting ##########
      # backtesting
      # --config /freqtrade/user_data/conf/config_freqaiRL_spot_telegram.json
      # --logfile /freqtrade/user_data/logs/freqtrade.log
      # --freqaimodel MyRLModelv8
      # --strategy-path /freqtrade/user_data/strategies
      # --strategy FreqaiRLStrategyWPv17
      # --timerange 20240124-20240224

      # hyperopt
      # --config /freqtrade/user_data/conf/config_freqaiRL_spot_telegram.json
      # --freqaimodel MyRLModelv8
      # --strategy-path /freqtrade/user_data/strategies
      # --strategy FreqaiRLStrategyWPv16
      # --timerange 20240124-20240224
      # --hyperopt-loss ScalpingTradeHyperOptLoss
      # --timeframe 4h
      # -e 500
      # --spaces buy sell stoploss trailing roi
      # --random-state 30

    #######  Freqai  ########
      # trade
      # --config /freqtrade/user_data/conf/config_freqaiRL_spot_telegram.json
      # --logfile /freqtrade/user_data/logs/freqtrade.log
      # --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      # --freqaimodel MyRLModelv8
      # --strategy-path /freqtrade/user_data/strategies
      # --strategy FreqaiRLStrategyWPv14


   ######## Download data ##########
      # download-data
      # --config /freqtrade/user_data/conf/config_freqaiRL_spot_telegram.json
      # --timerange 20200201-
      # --timeframes 1m 5m 15m 30m 1h 2h 4h 12h 1d
      